# Generated by Django 5.1.4 on 2025-01-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('pname', models.CharField(max_length=200)),
                ('pimage', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
