# Generated by Django 5.1.4 on 2025-01-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_item_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='details',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='cost',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
