# Generated by Django 5.1.4 on 2025-01-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_customer_product_customer_order_payment_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='payment_customer',
            name='order',
        ),
        migrations.DeleteModel(
            name='Product_customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment_customer',
        ),
    ]
