# Generated by Django 5.1.4 on 2025-01-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='upassword',
        ),
    ]
