# Generated by Django 5.1.4 on 2025-01-31 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_payment1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='webapp.payment1')),
            ],
        ),
    ]
