# Generated by Django 5.1.4 on 2025-01-31 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
