# Generated by Django 5.1.4 on 2025-02-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
