# Generated by Django 5.1.4 on 2025-02-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_contact_famount_contact_fdescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='famount',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='fdescription',
        ),
    ]
