# Generated by Django 5.1.4 on 2025-02-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_remove_contact_famount_remove_contact_fdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tranjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tran_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment1',
            name='product',
        ),
    ]
