# Generated by Django 5.1.4 on 2025-02-03 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_tranjection_remove_payment1_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tranjection',
        ),
        migrations.AddField(
            model_name='payment1',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.product'),
        ),
    ]
