# Generated by Django 5.1.4 on 2025-02-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_delete_tranjection_payment1_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment1',
            name='productamount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
