# Generated by Django 5.1.4 on 2025-02-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0034_cartitem_email_cartitem_fname_cartitem_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='phone',
        ),
    ]
