# Generated by Django 5.1.4 on 2025-02-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0036_cartitem_email_cartitem_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_amount',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
